version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/backend/src
    ports:
      - 4614:4614
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog-app
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-pass

volumes:
  mysql-volume: